### ISSUE TITLE
RestRequest not deallocating

### ISSUE THREAD

**Issue by schlingding** [IBM-Swift/SwiftyRequest#59]
In my codebase I use a `circuitBreaker`. Unless the circuitBreaker is set to nil after the response is complete the RestRequest will not deallocate.

**Comment by Andrew-Lees11** [comment]
Hello @schlingding 
Thank you for raising this issue. 
There was a retain cycle between RestRequest -> CircuitBreaker -> handleInvocation -> RestRequest
We have raise pr #60 which should fix this as well as the other memory leak issue which you references.

**Comment by djones6** [comment]
A fix has been delivered in [SwiftyRequest 2.0.6](https://github.com/IBM-Swift/SwiftyRequest/releases/tag/2.0.6) - please try this version at your convenience.

**Comment by schlingding** [comment]
I just updated to the latest version of SwiftyRequest and this issue is still persistent. I simply add a print statement to RestRequest.deinit and it will not be called until:
```
circuitBreaker = nil
circuitParameters = nil
```

**Comment by ianpartridge** [comment]
Oh dear. Thanks for reporting, we'll take another look asap.

**Comment by Andrew-Lees11** [comment]
@schlingding 
Sorry for closing early. With the latest fixes I was seeing the RestRequest being deallocated when using circuit breaker.
Would you be able to provide a code example to recreate the memory leak?

**Comment by schlingding** [comment]
It looks like this fix is deallocating as intended after all. Please disregard and thank you for all your help!

**Comment by ianpartridge** [comment]
You're welcome - thanks for reporting it!
